* Location of AAA additions used in add-ons

$ifi %OFFSHOREGRID%==yes  $include   "../../base/addons/offshoregrid/bb4/offshoregrid_aaaadditions.inc";
$ifi %INDUSTRY%==yes       $include   "../../base/addons/industry/bb4/industry_aaaadditions.inc";
$ifi %INDIVUSERS%==yes       $include   "../../base/addons/indivusers/bb4/indivusers_aaaadditions.inc";   
$ifi %ANTBALM%==yes       $include   "../../base/addons/antbalm/bb4/antbalm_aaaadditions.inc";   




