

$ifi %TRANSPORT%==yes       $include   "../../base/addons/transport/bb4/transport_de_var_tadditions.inc";
$ifi %INDIVUSERS%==yes       $include   "../../base/addons/indivusers/bb4/indivusers_de_var_tadditions.inc"; 
*$ifi %INDUSTRY%==yes       $include   "../../base/addons/industry/bb4/industry_de_var_tadditions.inc"; 
$ifi %ANTBALM%==yes       $include   "../../base/addons/antbalm/bb4/antbalm_de_var_tadditions.inc"; 









