

$ifi %INDUSTRY%==yes       $include   "../../base/addons/industry/bb4/industry_gkfxadditions.inc";
$ifi %INDIVUSERS%==yes       $include   "../../base/addons/indivusers/bb4/indivusers_gkfxadditions.inc";
$ifi %HYDROGEN%==yes  $include   "../../base/addons/hydrogen/bb4/hydrogen_gkfxadditions.inc";

* Need to be put last, because it significantly alters GKFX
$ifi %ANTBALM%==yes  $include   "../../base/addons/antbalm/bb4/antbalm_gkfxadditions.inc";  









