PARAMETERS

ANTBALM_MAXDEM(YYY, RRR) 'The maximum exogenous demand in all stochastic years of Antares, weighted to corresponding Balmorel regions'
ANTBALM_GCAPCRED(YYY, RRR, GGG) 'The capacity credit of a technology'
ANTBALM_XCAPCRED(YYY, RRR, RRR) 'The capacity credit of an electricity transmission line'
ANTBALM_RESMAR(YYY, RRR) 'The electricity reserve margin, a factor on maximum demand that defines minimum capacity' 
ANTBALM_H2MAXDEM(YYY, RRR) 'The maximum exogenous demand in all stochastic years of Antares, weighted to corresponding Balmorel regions'
ANTBALM_XH2CAPCRED(YYY, RRR, RRR) 'The capacity credit of a hydrogen transmission line'
ANTBALM_H2RESMAR(YYY, RRR) 'The hydrogen reserved margin, a factor on maximum demand that defines minimum capacity' 
